image: docker:18.09
services:
  - name: docker:18.09-dind
    command: [ "--tls=false", "--mtu=1240" ]

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

stages:
  - build
  - deploy

build_image:
  stage: build
  only:
    - stage
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/igrpweb-horizon/igrpweb1::$CI_PIPELINE_ID .
    - docker tag $CI_REGISTRY/igrpweb-horizon/igrpweb1::$CI_PIPELINE_ID $CI_REGISTRY/igrpweb-horizon/igrpweb1:latest
    - docker push $CI_REGISTRY/igrpweb-horizon/igrpweb1::$CI_PIPELINE_ID
    - docker push $CI_REGISTRY/igrpweb-horizon/igrpweb1::latest

deploy:
  stage: deploy
  only:
    - stage
  image: golang:latest
  script:
    - chmod +x deployment.sh; ./deployment.sh
