stages:
- name: compile & war generate
  steps:
  - runScriptConfig:
      image: maven:3.8.5-openjdk-17
      shellScript: mvn clean package
- name: code check
  steps:
  - runScriptConfig:
      image: maven:3.8.5-openjdk-17
      shellScript: |-
        mvn clean verify sonar:sonar \
          -Dsonar.projectKey=igrp-web_igrp-web-framework_AYba8-gdltjb8mcsAUNz \
          -Dsonar.host.url=https://code-sec.nosi.cv \
          -Dsonar.login=sqp_8dd11356fe614f5314b36d5f70d1b1fe9b9f7fad
- name: container
  steps:
  - publishImageConfig:
      dockerfilePath: ./data/Dockerfile
      buildContext: .
      tag: registry.nosi.cv/igrpweb-mhorizon/igrpweb:1.0
      pushRemote: true
      registry: registry.nosi.cv
timeout: 10
notification: {}
