stages:
- name: compile & war generate
  steps:
  - runScriptConfig:
      image: maven:3.8.5-openjdk-17
      shellScript: mvn clean package
- name: container
  steps:
  - publishImageConfig:
      dockerfilePath: ./data/Dockerfile
      buildContext: .
      tag: registry.nosi.cv/igrpweb-horizon/igrpweb:2.0
      pushRemote: true
      registry: registry.nosi.cv
- name: redeploy
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        curl -u "$user:$password" \
        -X POST \
        -H 'Accept: application/json' \
        -H 'Content-Type: application/json' \
        --insecure 'https://manager.nosi.cv/v3/project/c-cpx7p:p-mkpb6/workloads/statefulset:horizon:igrp1?action=redeploy'
    envFrom:
    - sourceName: api-redeploy
      sourceKey: access
      targetKey: user
    - sourceName: api-redeploy
      sourceKey: secret
      targetKey: password
timeout: 10
notification: {}
